### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by glixzzy** [FancyWaifu/Easy-Blooket#1]
skidddddd

**Comment by glixzzy** [comment]
your a skid

**Comment by FancyWaifu** [comment]
> your a skid

Idk what that means

**Comment by glixzzy** [comment]
tf? you stole code from https://github.com/iCrazeiOS/Blooket-Scripts

**Comment by glixzzy** [comment]
and do u even know what skid means? lol stealing others code and making it loook like you made it

**Comment by FancyWaifu** [comment]
Whoops, sorry my bad, I forgot to credit him, ur probably won’t believe but I forgot to do that, also u didn’t need to be an asshole about, could have been like “Hey, I saw that this piece of code was written by this person and you didn’t credit them, did u mean to do this?” And I would have been like “Oh my bad, I forgot to credit him, let me go do that really fast”. Easy problem solved

**Comment by glixzzy** [comment]
um, I’m sorry I regret acting like an asshole I should have said it nicely.. i am really sorry..
